Repository ceph/go-ceph, pull requests merged in 2021-09, with the labels that each got.

#570 cephfs : add missing cephfs API components: fuction ceph_version
  cephfs/cephfs.go
  cephfs/cephfs_test.go
Labels: API

#575 rados: add missing error asserts
  rados/rados_test.go
Labels: small

#578 entrypoint: show return values of tests
  entrypoint.sh
Labels: small

#571 rgw/admin: add apis for handling UserCap
  rgw/admin/caps.go
  rgw/admin/caps_test.go
  rgw/admin/errors.go
Labels: extended review, API
