Repository ceph/go-ceph, pull requests merged in 2021-08, with the labels that each got.

#546 rgw/admin: include stat information to User Struct
  rgw/admin/user.go
  rgw/admin/user_test.go
Labels: API

#550 rbd: deprecate Close() method of MirrorImageGlobalStatusIter
  rbd/mirror.go
Labels: small, API

#527 rbd: export mirror image list functions
  rbd/mirror.go
  rbd/mirror_test.go
Labels: API

#553 cutil: fix race condition in ptrguard tests
  internal/cutil/ptrguard_test.go
Labels: small

#561 rbd: implement binding for rbd_mirror_image_instance_id_list
  rbd/mirror.go
  rbd/mirror_test.go
Labels: API
