Repository ceph/go-ceph, pull requests merged in 2022-02, with the labels that each got.

#637 make: always rebuild implements.json
  Makefile
Labels: small, no-API

#639 containers: disable a repo to get the ci up and going again
  testing/containers/ceph/Dockerfile
Labels: no-API

#631 rados: implement binding for rados_write_op_remove
  docs/api-status.json
  docs/api-status.md
  rados/rados_write_op_remove.go
  rados/rados_write_op_remove_test.go
Labels: API

#632 rados: implement binding for rados_{read,write}_op_assert_version
  docs/api-status.json
  docs/api-status.md
  rados/rados_read_op_assert_version.go
  rados/rados_read_op_assert_version_test.go
  rados/rados_write_op_assert_version.go
  rados/rados_write_op_assert_version_test.go
Labels: API

#633 rbd: update doc comments for rbd image Read and Write funcs
  rbd/rbd.go
Labels: no-API

#638 common: implement a common log package
  common/log/log.go
  internal/log/log.go
  internal/log/log_test.go
Labels: API
