Repository ceph/go-ceph, pull requests merged in 2022-06, with the labels that each got.

#691 cephfs: add subvolume metadata APIs
  cephfs/admin/fsadmin.go
  cephfs/admin/metadata.go
  cephfs/admin/metadata_test.go
Labels: API

#698 cephfs: add subvolume snapshot metadata APIs
  cephfs/admin/snapshot_metadata.go
  cephfs/admin/snapshot_metadata_test.go
Labels: API

#705 cephfs admin: remove deprecated EnableModule, DisableModule funcs
  cephfs/admin/mgrmodule.go
  docs/api-status.json
Labels: no-API

#707 readme: note v0.16.0 has preliminary quincy support
  README.md
Labels: no-API

#700 rbd: don't cap the buffer size used in GetImageNames
  rbd/rbd_nautilus.go
Labels: no-API

#715 makefile: use `pacific` as our default ceph version
  Makefile
Labels: no-API

#716 fix: fixed few typos
  docs/api-stability.md
Labels: no-API

#724 CI: also disable TestCancelClone for pacific
  cephfs/admin/clone_test.go
Labels: no-API

#721 cephfs/admin: Fix compile errors
  cephfs/admin/snapshot_metadata_test.go
Labels: no-API

#727 Add MacOS instructions to README
  README.md
Labels: small, no-API

#723 CI: remove non-ptrguard tests
  .github/workflows/main.yml
Labels: no-API

#725 Makefile: Use `?=` for initial variable definitions
  Makefile
Labels: no-API
