Repository ceph/go-ceph, pull requests merged in 2022-07, with the labels that each got.

#713 rados: Make sure Conn isn't GC'd while it has dependant IOContexts.
  rados/conn.go
  rados/ioctx.go
Labels: no-API

#710 rados: Implement rados_set_alloc_hint2
  docs/api-status.json
  docs/api-status.md
  rados/alloc_hint_flags.go
  rados/ioctx_set_alloc_hint.go
  rados/ioctx_set_alloc_hint_test.go
  rados/write_op_set_alloc_hint.go
  rados/write_op_set_alloc_hint_test.go
Labels: API

#732 gitignore: Add vi/vim backup files
  .gitignore
Labels: small, no-API

#733 entrypoint: Store bootstrap token in variable
  entrypoint.sh
Labels: no-API

#731 go-ceph: bump Go version of module to 1.17
  go.mod
Labels: small, no-API

#714 rbd: add mirroring support for nautilus
  entrypoint.sh
  rbd/mirror.go
  rbd/mirror_nautilus.go
  rbd/mirror_nautilus_test.go
  rbd/mirror_test.go
Labels: API

#704 Rgw/admin: add num_shards to bucket struct field
  rgw/admin/bucket.go
Labels: API

#746 github: update dependabot configuration to better match go-ceph style
  .github/dependabot.yml
Labels: no-API
