Repository ceph/go-ceph, pull requests merged in 2025-01, with the labels that each got.

#1046 rgw/admin: support new-bucket-name for LinkBucket
  rgw/admin/link.go
  rgw/admin/link_test.go
Labels: API

#1060 workflows: remove pre-quincy job
  .github/workflows/main.yml
Labels: no-API

#1062 Makefile: Remove leftovers related to EOL releases
  Makefile
Labels: no-API

#1067 rbd: fix cleanup of GroupSnapRollback and Sparsify progress callbacks
  rbd/group_snap.go
  rbd/sparsify.go
Labels: bug, no-API
